gui:
  theme:
    activeBorderColor:
      - '#a6da95'
      - bold
    inactiveBorderColor:
      - '#b8c0e0'
    optionsTextColor:
      - '#8aadf4'
    selectedLineBgColor:
      - '#6e738d'
    cherryPickedCommitBgColor:
      - '#494d64'
    cherryPickedCommitFgColor:
      - '#a6da95'
    unstagedChangesColor:
      - '#ed8796'
    defaultFgColor:
      - '#cad3f5'
    searchingActiveBorderColor:
      - '#eed49f'

  authorColors:
    '*': '#eed49f'
  showBottomLine: false
  commandLogSize: 3
  showCommandLog: true

keybinding:
  universal:
    gotoTop: g
    gotoBottom: G
  commits:
    viewResetOptions: <c-g>
  stash:
    popStash: <c-g>
